export const copyZh = {
  common: {
    brand: "OnePitch · 一眼项目",
    loading: "加载中...",
  },
  landing: {
    navTag: "把模糊想法变成能发出去的项目卡",
    navExplore: "查看项目库",
    navStart: "登录后继续编辑",
    heroTitleLines: ["把一个想法、定位或进展", "压成一张能直接发出去的", "项目卡"],
    heroSubtitle: "写一句让外部人快速判断价值的话，我们会把它压成可直接转发的项目卡。",
    socialProof: "已服务 50+ OPC 项目",
    promptPlaceholder: "写一句让外部人立刻懂你项目的话",
    promptHint: "点我填入示例：让投资人 3 分钟决定要不要继续聊",
    promptEmptyHint: "输入一句话后即可生成项目卡",
    heroHighlights: ["一句话会被拆成项目名称、问题、方案和目标用户", "生成后可直接复制链接或制作分享海报", "需要修改时再登录认领，不打断第一次体验"],
    jumpToCta: "生成项目卡",
    browsePublic: "查看项目库",
    valueTitle: "这不是教程，而是 OnePitch 的表达原则",
    valueLead: "先做出能发出去的对象，再把编辑留在更靠后的一步。",
    valueItems: [
      {
        title: "先给外部判断线索，不先写长文档",
        desc: "先让对方知道值不值得继续聊。",
      },
      {
        title: "先发出去，再拿真实反馈回来",
        desc: "传播是验证的一部分，不是最后一步。",
      },
      {
        title: "需要时再认领，不打断第一次表达",
        desc: "第一次先完成，后续再持续完善。",
      },
    ],
    exampleTitle: "示例项目",
    exampleSubtitle: "先看成品长什么样，再决定你自己的那一句话怎么写。",
    exampleTry: "我也生成一个类似的",
    exampleViewCard: "查看项目卡",
    exampleRealtime: "示例可直接回填到输入框",
    exampleLoading: "正在加载公开项目示例...",
    exampleEmpty: "公开项目还在积累中，先体验创建流程。",
    showcaseTrackAria: "示例项目轮播区",
    showcasePrevAria: "查看上一个案例",
    showcaseNextAria: "查看下一个案例",
    showcaseOpenAriaPrefix: "打开案例",
    showcaseDotAria: (index: number) => `查看第 ${index} 个案例`,
    workflowTitle: "生成之后会发生什么",
    workflowSteps: [
      {
        title: "输入一句话",
        desc: "先把你脑子里那句最粗糙的描述写出来，不需要先想结构。",
      },
      {
        title: "自动压缩成项目卡",
        desc: "系统会把输入拆成标题、摘要、状态、问题、方案和下一步计划。",
      },
      {
        title: "直接发出去",
        desc: "你可以先复制链接或生成海报，等需要再回来认领和编辑。",
      },
    ],
    ctaTitle: "先做出第一张卡，再决定要不要长期保存",
    ctaDesc: "如果这张卡值得发出去，再回来认领并继续编辑。",
    emailPlaceholder: "请输入邮箱，例如 you@company.com",
    codePlaceholder: "请输入 6 位验证码",
    loginButton: "邮箱登录并继续编辑",
    loggingIn: "登录中...",
    sendingCode: "发送验证码中...",
    sendCode: "发送验证码",
    verifyCode: "验证并登录",
    verifyingCode: "验证中...",
    codeSentHint: "验证码已发送到你的邮箱。",
    codeResentHint: "验证码已重新发送，请查收邮箱。",
    resendCode: "重新发送",
    resendReady: "可重新发送验证码。",
    resendIn: (seconds: number) => `可在 ${seconds}s 后重新发送`,
    debugCodeHint: "开发模式验证码：",
    switchEmail: "修改邮箱",
    loginFailed: "登录失败，请稍后重试。",
    loginTimeout: "服务启动较慢，请稍后重试（无需连续点击）。",
    explorePublic: "先看公开项目",
  },
  library: {
    title: "公开项目库",
    subtitle: "看看别人怎么描述他们的项目，然后创建你自己的。",
    backLanding: "回到首页",
    searchPlaceholder: "搜索项目（标题 / 关键词 / ID）",
    createProject: "创建项目",
    createNeedLogin: "登录后可创建项目",
    signedInAs: "当前登录",
    logout: "退出登录",
    loggingOut: "退出中...",
    exportBackup: "导出我的备份",
    exportingBackup: "导出中...",
    filterAll: "全部",
    filterPublic: "仅公开",
    filterMine: "我的项目",
    statAll: "项目总数",
    statPublic: "公开项目",
    statMine: "我的项目",
    filterFormLabel: "产品形态",
    filterUsersLabel: "目标用户",
    filterBusinessLabel: "商业模式",
    filterModelLabel: "盈利模式",
    filterAnyForm: "全部产品形态",
    filterAnyUsers: "全部目标用户",
    filterAnyBusiness: "全部商业模式",
    filterAnyModel: "全部盈利模式",
    loadingProjects: "正在加载项目...",
    loadingCards: "正在加载项目卡片...",
    loadFailed: "加载项目失败，请稍后重试。",
    loadTimeout: "请求超时，请稍后点击重试。",
    invalidResponse: "服务响应异常，请稍后重试。",
    retryLoad: "重试加载",
    healthChecking: "服务状态：检测中",
    healthOk: "服务状态：正常",
    healthDown: "服务状态：异常",
    emptyHint: "还没有项目？先看看精选案例。",
    openDemo: "查看示例项目",
  },
  projectCard: {
    noSummary: "暂无摘要",
    public: "公开",
    private: "私有",
    stage: "发展阶段",
    stageFallback: "阶段待定",
    form: "产品形态",
    users: "目标用户",
    businessModel: "商业模式",
    profitModel: "盈利模式",
    usersFallback: "待补充",
    valueFallback: "待补充",
    latest: "最近更新",
    noUpdates: "暂无更新",
    viewDetails: "查看项目卡",
    editCard: "编辑项目卡",
  },
  create: {
    title: "描述你的项目",
    subtitle: "输入一句话、项目名，或直接粘贴已有内容，系统会生成可编辑的项目卡对象。",
    inputPlaceholder: "用一句话描述你的项目，或直接输入项目名称，也可以粘贴已有内容 / BP",
    addMaterial: "＋ 添加材料",
    dropHint: "支持拖拽 PDF 到输入区",
    attachedPrefix: "已附加",
    generate: "生成项目卡",
    generating: "生成中...",
    shortcutHint: "⌘ + Enter 快速生成",
    draftTitle: "项目草稿已生成",
    draftSubtitle: "你的项目已经成型，可以直接用于展示或分享，你只需要微调表达",
    draftReadyState: "已生成 · 可直接分享",
    clickToEdit: "点击修改",
    titleFallback: "未命名项目",
    fieldEmpty: "点击补充这部分内容",
    progressEmpty: "补充一条最近发生的关键进展事件",
    fieldTitle: "项目标题",
    fieldWhat: "项目简介",
    fieldMonetization: "商业模式",
    fieldCurrentState: "当前状态",
    fieldProgress: "最近进展",
    fieldMetric: "关键指标",
    stateIdea: "构思阶段",
    stateBuilding: "构建中",
    stateLaunched: "已上线",
    copyShareLink: "复制项目卡链接",
    previewSharePage: "查看项目卡预览",
    copied: "分享链接已复制。",
    saveFailed: "保存失败，请稍后重试。",
    createFailed: "生成失败，请稍后重试。",
    createNetworkFailed: "请求可能已提交，请先到项目库刷新确认，避免重复创建。",
    fallbackWarning: "本次使用了本地兜底结构化结果。",
    advancedToggle: "上传 BP（PDF，10MB 内）",
    uploadHint: "仅提取文本用于 AI 结构化，不存储原始文件，请勿上传敏感商业信息。",
    uploadParsing: "正在解析文件...",
    uploadParsed: "解析完成",
    uploadFailed: "文件解析失败，请检查 PDF 后重试。",
    uploadTypeInvalid: "仅支持 PDF 文件（.pdf）。",
    uploadTooLarge: "文件过大，请上传 10MB 以内 PDF。",
    uploadMergedHint: "材料已加入本次生成语料。",
    missingInput: "请先输入描述，或添加材料。",
    continueEditHint: "字段失焦后会自动保存。",
    autoSaveSaving: "正在自动保存...",
    autoSaveSaved: "已自动保存",
    shareActionsHint: "你可以直接分享，也可以继续优化表达。",
    needLoginTitle: "需要先登录",
    needLoginDesc: "未登录用户可以浏览公开项目，但不能创建或编辑项目卡。",
    authCheckFailed: "登录状态检查失败，请重试或返回首页重新登录。",
    retryAuthCheck: "重试检查",
    goLogin: "返回首页登录",
    uploadNetworkFailed: "上传解析超时，请稍后重试。",
  },
  detail: {
    loadFailed: "加载项目失败，请稍后重试。",
    loadingProject: "正在加载项目...",
    noSummary: "暂无摘要",
    brand: "OnePitch · 一眼项目",
    backLibrary: "返回我的项目",
    openShare: "查看项目卡",
    profileTitle: "项目信息",
    expressionTitle: "核心表达",
    businessTitle: "受众与经营",
    progressInfoTitle: "当前进展",
    businessHint: "商业模式：面向谁卖；盈利模式：怎么赚钱。",
    fieldSummary: "项目简介",
    fieldModel: "盈利说明",
    fieldModelType: "盈利模式",
    fieldBusinessModel: "商业模式",
    fieldProblem: "核心问题",
    fieldSolution: "解决方案",
    fieldUseCases: "使用场景",
    fieldFormType: "产品形态",
    fieldStage: "发展阶段",
    fieldUsers: "目标用户",
    fieldEmpty: "待补充",
    fieldEdit: "编辑",
    fieldSave: "保存",
    fieldCancel: "取消",
    savedHint: "已保存",
    stateTitle: "当前状态",
    public: "公开",
    private: "私有",
    noUpdates: "暂无进展",
    updateTitle: "更新进展",
    updatePlaceholder: "描述你最近的关键进展",
    submitUpdate: "添加进展",
    addProgress: "添加进展",
    cancel: "取消",
    updating: "更新中...",
    saving: "保存中...",
    makePrivate: "设为私有",
    makePublic: "设为公开",
    editProject: "编辑项目信息",
    updateFailed: "更新失败，请稍后重试。",
    projectTitlePlaceholder: "项目标题",
    manageMenu: "更多操作",
    deleteProject: "删除项目",
    deleting: "删除中...",
    deleteConfirm: "确认删除该项目？此操作不可撤销。",
    deleteFailed: "删除项目失败，请稍后重试。",
    timelineTitle: "项目进展",
    editFailed: "保存修改失败，请稍后重试。",
    shareToggleFailed: "切换公开状态失败，请稍后重试。",
  },
  share: {
    title: "项目卡",
    backHome: "返回首页",
    backLibrary: "返回公开项目库",
    backEdit: "返回编辑页",
    backDraft: "返回继续编辑",
    loading: "正在加载...",
    loadFailed: "加载项目卡失败，请稍后重试。",
    loadTimeout: "加载超时，请稍后重试。",
    privateMessage: "该项目当前为私有，仅项目所有者可预览。",
    noSummary: "暂无摘要",
    problem: "问题",
    solution: "解决方案",
    useCases: "使用场景",
    cta: "我也做一张项目卡",
    ownershipHint: "这是你刚刚生成的第一张项目卡",
    editToClaim: "改一下再发",
    editCard: "编辑项目卡",
    ctaFailed: "操作失败，请稍后重试。",
    ctaTimeout: "请求超时，请稍后重试。",
    retryLoad: "重新加载",
    posterButton: "生成分享海报",
    posterGenerating: "正在生成海报...",
    posterOnlyPublic: "仅公开项目支持生成海报。",
    posterDone: "海报已生成并开始下载。",
    posterFailed: "海报生成失败，请稍后重试。",
    copyLinkButton: "复制分享链接",
    copyLinkDone: "分享链接已复制，可粘贴到浏览器或微信聊天。",
    copyLinkFailed: "复制失败，请手动复制地址栏链接。",
    wechatFallbackHint: "若微信内无法直接打开，请先复制链接到系统浏览器，或优先使用海报二维码分享。",
  },
} as const;
