export const copyZh = {
  common: {
    brand: "OneFile",
    loading: "加载中...",
  },
  landing: {
    navTag: "专为 OPC 与早期创业者设计",
    navExplore: "浏览案例",
    navStart: "邮箱登录",
    heroTitle: "把想法变成可演化的项目资产",
    heroSubtitle: "面向一人公司与早期创业者，把零散灵感结构化、可持续演化，并直接用于对外表达。",
    socialProof: "已帮助 50+ OPC 把零散想法变成可展示的项目名片。",
    heroHighlights: [
      "结构化表达：快速形成可读项目档案",
      "演化沉淀：每次更新都进入时间线",
      "分享回流：外部访问可引导创建新项目",
    ],
    jumpToCta: "开始使用",
    browsePublic: "浏览公开项目",
    valueTitle: "核心价值",
    valueItems: [
      {
        title: "结构化表达",
        desc: "把想法快速整理为可读的项目档案，清晰呈现问题、方案与目标用户。",
      },
      {
        title: "持续演化",
        desc: "每次更新沉淀为时间线证据，帮助你追踪项目从想法到落地的变化过程。",
      },
      {
        title: "传播回流",
        desc: "通过分享页展示项目价值，并将访问者引导回 OneFile 创建自己的项目。",
      },
    ],
    exampleTitle: "示例项目卡片",
    exampleSubtitle: "先看别人如何表达，再创建你自己的项目。",
    exampleRealtime: "数据来源：实时公开项目",
    exampleLoading: "正在加载公开项目示例...",
    exampleEmpty: "公开项目还在积累中，先体验创建流程。",
    workflowTitle: "三步完成项目表达",
    workflowSteps: [
      {
        title: "输入想法",
        desc: "用自然语言描述你的项目目标、用户与当前阶段。",
      },
      {
        title: "AI 结构化",
        desc: "系统将内容整理成可读项目档案，并生成下一步动作建议。",
      },
      {
        title: "持续更新与分享",
        desc: "记录关键进展并分享给外部用户，形成增长回流闭环。",
      },
    ],
    ctaTitle: "现在开始创建你的项目档案",
    ctaDesc: "继续使用邮箱登录，进入项目库后即可开始创建与持续更新。",
    emailPlaceholder: "请输入邮箱，例如 you@company.com",
    codePlaceholder: "请输入 6 位验证码",
    loginButton: "邮箱登录并进入项目库",
    loggingIn: "登录中...",
    sendingCode: "发送验证码中...",
    sendCode: "发送验证码",
    verifyCode: "验证并登录",
    verifyingCode: "验证中...",
    codeSentHint: "验证码已发送到你的邮箱。",
    debugCodeHint: "开发模式验证码：",
    switchEmail: "修改邮箱",
    loginFailed: "登录失败，请稍后重试。",
    explorePublic: "先逛公开项目库",
  },
  library: {
    title: "公开项目库",
    subtitle: "看看别人怎么描述他们的项目，然后创建你自己的。",
    backLanding: "回到首页",
    searchPlaceholder: "搜索项目",
    createProject: "创建项目",
    createNeedLogin: "登录后可创建项目",
    signedInAs: "当前登录",
    logout: "退出登录",
    loggingOut: "退出中...",
    exportBackup: "导出我的备份",
    exportingBackup: "导出中...",
    filterAll: "全部",
    filterPublic: "仅公开",
    filterMine: "我的项目",
    statAll: "项目总数",
    statPublic: "公开项目",
    statMine: "我的项目",
    filterFormLabel: "产品形态",
    filterUsersLabel: "目标用户",
    filterModelLabel: "商业模式",
    filterAnyForm: "全部产品形态",
    filterAnyUsers: "全部目标用户",
    filterAnyModel: "全部商业模式",
    loadingProjects: "正在加载项目...",
    loadingCards: "正在加载项目卡片...",
    loadFailed: "加载项目失败，请稍后重试。",
    emptyHint: "还没有项目？先看看精选案例。",
    openDemo: "查看示例项目",
  },
  projectCard: {
    noSummary: "暂无摘要",
    public: "公开",
    private: "私有",
    stage: "发展阶段",
    stageFallback: "阶段待定",
    form: "产品形态",
    users: "目标用户",
    model: "商业模式",
    usersFallback: "待补充",
    valueFallback: "待补充",
    latest: "最近更新",
    noUpdates: "暂无更新",
    viewDetails: "查看完整档案",
    sharePage: "分享页",
  },
  create: {
    title: "创建项目档案",
    subtitle: "默认只需描述你的项目想法，OneFile 会自动结构化。",
    cardTitle: "新建项目",
    entityLabel: "主体名称（必填）",
    entityRequired: "请先填写主体名称。",
    entityHint: "请填写个人/团队/工作室/公司名称，勿填写项目功能描述。",
    namePlaceholder: "例如：老王独立开发 / 星云小团队 / 法智AI工作室",
    inputPlaceholder: "描述你的想法、目标用户和当前进展",
    nameTooShort: "主体名称过短，建议至少 2 个字符。",
    nameTooLong: "主体名称过长，请控制在 30 个字符以内。",
    nameKeywordHint: "检测到描述型关键词，建议填写主体名称而不是项目功能描述。",
    advancedToggle: "高级：上传 BP（PDF，10MB 内）",
    uploadHint: "仅提取文本用于 AI 结构化，不存储原始文件，请勿上传敏感商业信息。",
    uploadSelect: "选择 PDF 文件",
    uploadParsing: "正在解析文件...",
    uploadParsed: "解析完成",
    uploadFailed: "文件解析失败，请检查 PDF 后重试。",
    uploadTypeInvalid: "仅支持 PDF 文件（.pdf）。",
    uploadTooLarge: "文件过大，请上传 10MB 以内 PDF。",
    uploadMergedHint: "创建时将自动合并上传文本。",
    submit: "生成项目",
    submitting: "生成中...",
    backLibrary: "返回项目库",
    missingEmail: "缺少登录邮箱，请先回到首页登录。",
    needLoginTitle: "需要先登录",
    needLoginDesc: "未登录用户可以浏览公开项目，但不能创建或编辑档案。",
    goLogin: "返回首页登录",
    createFailed: "创建失败，请稍后重试。",
    fallbackWarning: "本次使用了本地兜底结构化结果。",
  },
  detail: {
    loadFailed: "加载项目失败，请稍后重试。",
    loadingProject: "正在加载项目...",
    noSummary: "暂无摘要",
    backLibrary: "返回项目库",
    openShare: "打开分享页",
    stateTitle: "当前状态",
    public: "公开",
    private: "私有",
    nextAction: "下一步动作",
    noAction: "暂无动作",
    latestUpdate: "最近更新",
    noUpdates: "暂无更新",
    updateTitle: "更新进展",
    updatePlaceholder: "描述你最近的关键进展",
    submitUpdate: "提交更新",
    updating: "更新中...",
    saving: "保存中...",
    makePrivate: "设为私有",
    makePublic: "设为公开",
    updateFailed: "更新失败，请稍后重试。",
    advancedTitle: "高级编辑",
    projectTitlePlaceholder: "项目标题",
    summaryPlaceholder: "一句话摘要",
    saveAdvanced: "保存高级编辑",
    deleteProject: "删除项目",
    deleting: "删除中...",
    deleteConfirm: "确认删除该项目？此操作不可撤销。",
    deleteFailed: "删除项目失败，请稍后重试。",
    timelineTitle: "更新时间线",
    ownerOnlyHint: "你当前是浏览模式。登录且为项目所有者后，才可更新、编辑和修改公开状态。",
    editFailed: "保存高级编辑失败，请稍后重试。",
    shareToggleFailed: "切换公开状态失败，请稍后重试。",
    timelineKindFallback: "进展",
    evidence: "证据",
    alignment: "对齐",
  },
  share: {
    title: "项目分享页",
    backLibrary: "返回公开项目库",
    loading: "正在加载...",
    loadFailed: "加载分享页失败，请稍后重试。",
    privateMessage: "该项目当前为私有，仅项目所有者可预览。",
    noSummary: "暂无摘要",
    problem: "问题",
    solution: "解决方案",
    useCases: "使用场景",
    cta: "用 OneFile 创建你的项目档案 →",
    ctaFailed: "操作失败，请稍后重试。",
    posterButton: "生成分享海报",
    posterGenerating: "正在生成海报...",
    posterOnlyPublic: "仅公开项目支持生成海报。",
    posterDone: "海报已生成并开始下载。",
    posterFailed: "海报生成失败，请稍后重试。",
    copyLinkButton: "复制分享链接",
    copyLinkDone: "分享链接已复制，可粘贴到浏览器或微信聊天。",
    copyLinkFailed: "复制失败，请手动复制地址栏链接。",
    wechatFallbackHint: "若微信内无法直接打开，请先复制链接到系统浏览器，或优先使用海报二维码分享。",
  },
} as const;
